#!/usr/bin/env python
"""Create deploy/env/local.env with local-only secrets for Docker Compose.

The generated file is gitignored. It is safe to run repeatedly; existing values are
preserved unless --force is passed.
"""

from __future__ import annotations

import argparse
import base64
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV_DIR = ROOT / "env"
LOCAL_ENV = ENV_DIR / "local.env"


def _token(nbytes: int = 32) -> str:
    return secrets.token_urlsafe(nbytes)


def _render() -> str:
    password = _token(24)
    web_secret = _token(48)
    fernet = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode("ascii")
    return f"""# Generated by deploy/init-local-env.py. Do not commit.
POSTGRES_DB=qa_workflow
POSTGRES_USER=qa_workflow
POSTGRES_PASSWORD={password}

QA_WEBAPP_DATABASE_URL=postgresql+psycopg://qa_workflow:{password}@postgres:5432/qa_workflow
QA_WEBAPP_SECRET={web_secret}
QA_FERNET_KEYS={fernet}
QA_WEBAPP_SECURE_COOKIE=0
QA_WEBAPP_PORT=8800
QA_WEBAPP_CONCURRENCY=4
QA_USE_WORKER=1
QA_USE_DB_ARTIFACTS=1
QA_KB_STRICT=1
QA_DB_POOL_SIZE=5
QA_DB_MAX_OVERFLOW=5
QA_DB_POOL_RECYCLE=3600
QA_QUEUE_POOL_MIN_SIZE=1
QA_QUEUE_POOL_MAX_SIZE=2
QA_QUEUE_POOL_MAX_LIFETIME=3600
QA_GENERATION_WORKER_CONCURRENCY=3
QA_REVIEW_WORKER_CONCURRENCY=6
QA_JIRA_RATE_QPS=1
QA_JIRA_RATE_BURST=5
QA_JIRA_CACHE_TTL_SECONDS=900
QA_QUEUE_DEPTH_WARN=50
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate gitignored deploy/env/local.env")
    parser.add_argument("--force", action="store_true", help="overwrite existing local.env")
    args = parser.parse_args()

    ENV_DIR.mkdir(parents=True, exist_ok=True)
    if LOCAL_ENV.exists() and not args.force:
        print(f"exists: {LOCAL_ENV}")
        return 0
    LOCAL_ENV.write_text(_render(), encoding="utf-8")
    print(f"wrote: {LOCAL_ENV}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
